You need to code to address the following problems:
<ol>
    <li>Load raw_bank_data.csv dataset.</li>
    <li>Check what types of attributes are available in the data.</li>
    <li>Check statistical information of numerical attributes.</li>
    <li>Check if there are missing data and noise for attributes.</li>
    <li>Choose mean or median values to fill the missing data.</li>
    <li>Drop those data records whose last column ("y") is missing.</li> 
    <li>Need to drop two columns "day" and "month".</li>
    <li>Normalize the categorical features using one-hot method.</li>   <font color=green>  
    <b>Below tasks are optional activities for 3031ICT:   
    <li>Use K-NN as a classifier to predict if the customer is going to have a deposit.</li>
    <li>Normalize the data using min-max scale and then perform the K-NN above again.</li>     
</ol>

In [285]:
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib as plt

df = pd.read_csv('raw_bank_data.csv', sep=',')

df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30.0,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33.0,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35.0,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30.0,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,NaN
4,59.0,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [286]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,4322.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,42.714253,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,15.785534,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,34.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,40.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,150.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

In [287]:
df.isnull().any()

age           True
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
y             True
dtype: bool

In [288]:
v1 = df['age'].mean(skipna=True)
print(v1)

42.71425266080518

In [289]:
values = {'age':v1}
clean_df = df.fillna(value=values)
clean_df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30.0,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33.0,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35.0,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30.0,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,NaN
4,59.0,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [290]:
clean_df.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
y             True
dtype: bool

In [291]:
nonan_clean_df=clean_df.dropna(axis=0,how='any')
nonan_clean_df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30.0,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33.0,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35.0,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
4,59.0,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
5,35.0,management,single,tertiary,no,747,no,no,cellular,23,feb,141,2,176,3,failure,no

In [292]:
nonan_clean_df.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
y            False
dtype: bool

In [293]:
nonan_clean_df_noday = nonan_clean_df.drop('day', axis=1)
nonan_clean_df_noday_nomonth = nonan_clean_df_noday.drop('month', axis=1)
nonan_clean_df_noday_nomonth.head()

,age,job,marital,education,default,balance,housing,loan,contact,duration,campaign,pdays,previous,poutcome,y
0,30.0,unemployed,married,primary,no,1787,no,no,cellular,79,1,-1,0,unknown,no
1,33.0,services,married,secondary,no,4789,yes,yes,cellular,220,1,339,4,failure,no
2,35.0,management,single,tertiary,no,1350,yes,no,cellular,185,1,330,1,failure,no
4,59.0,blue-collar,married,secondary,no,0,yes,no,unknown,226,1,-1,0,unknown,no
5,35.0,management,single,tertiary,no,747,no,no,cellular,141,2,176,3,failure,no

In [294]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30.0,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33.0,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35.0,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30.0,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,NaN
4,59.0,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [295]:
import numpy as np
import sklearn
from sklearn.metrics import *
from sklearn.svm import SVC, LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import minmax_scale
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer 
from sklearn import preprocessing

df = df.dropna()

for col_name in df.columns:
    if(df[col_name].dtype=='object'):
        df[col_name] = df[col_name].astype('category')
        df[col_name] = df[col_name].cat.codes

X = np.array(df.values[:,0:14])
y = np.array(df.values[:,-1])
print(len(df['job'].unique()),len(df['marital'].unique()),len(df['education'].unique()),len(df['default'].unique()),len(df['housing'].unique()),len(df['loan'].unique()),len(df['contact'].unique()),len(df['poutcome'].unique()))


#enc = OneHotEncoder(n_values = [12, 3, 4, 2, 2, 2, 3, 4], categorical_features=[1, 2, 3, 4, 6, 7, 8, 13])
#X = enc.fit_transform(X).toarray()

#enc = OneHotEncoder(categories=[range(12), range(3), range(4), range(2), range(2), range(2), range(3), range(4)], ColumnTransformer = [1, 2, 3, 4, 6, 7, 8, 13])

ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(),[1, 2, 3, 4, 6, 7, 8, 13])], remainder="passthrough")
X = ct.fit_transform(X)

print(X.shape)
print(X[0,:])
X_n= X     # original data
#X_n = minmax_scale(X)   # min max normalization
#X_n = preprocessing.scale(X)          # z-score normalization
print(X_n)

knn_params = {'n_neighbors': [1, 5, 10, 15]}
X_tr, X_te, ys_tr, ys_te = train_test_split( X_n, y, test_size = 0.3)
        
knn = KNeighborsClassifier()
clf = GridSearchCV(knn, knn_params, cv =2, n_jobs =1, verbose =3)
clf.fit(X_tr, ys_tr)
knn_pred = clf.predict(X_te)
accuracy = accuracy_score(ys_te, knn_pred)
print("KNN -> The best parameter is %.3f Accuracy: %.6f"%(clf.best_params_['n_neighbors'],accuracy))

12 3 4 2 2 2 3 4
(4230, 318)
  (0, 10)	1.0
  (0, 13)	1.0
  (0, 15)	1.0
  (0, 19)	1.0
  (0, 21)	1.0
  (0, 23)	1.0
  (0, 25)	1.0
  (0, 28)	1.0
  (0, 312)	30.0
  (0, 313)	1787.0
  (0, 314)	19.0
  (0, 315)	10.0
  (0, 316)	79.0
  (0, 317)	1.0
  (0, 10)	1.0
  (0, 13)	1.0
  (0, 15)	1.0
  (0, 19)	1.0
  (0, 21)	1.0
  (0, 23)	1.0
  (0, 25)	1.0
  (0, 28)	1.0
  (0, 312)	30.0
  (0, 313)	1787.0
  (0, 314)	19.0
  (0, 315)	10.0
  (0, 316)	79.0
  (0, 317)	1.0
  (1, 7)	1.0
  (1, 13)	1.0
  (1, 16)	1.0
  (1, 19)	1.0
  (1, 22)	1.0
  (1, 24)	1.0
  (1, 25)	1.0
  (1, 250)	1.0
  (1, 312)	33.0
  (1, 313)	4789.0
  (1, 314)	11.0
  :	:
  (4228, 16)	1.0
  (4228, 19)	1.0
  (4228, 21)	1.0
  (4228, 23)	1.0
  (4228, 25)	1.0
  (4228, 165)	1.0
  (4228, 312)	28.0
  (4228, 313)	1137.0
  (4228, 314)	6.0
  (4228, 315)	3.0
  (4228, 316)	129.0
  (4228, 317)	4.0
  (4229, 2)	1.0
  (4229, 14)	1.0
  (4229, 17)	1.0
  (4229, 19)	1.0
  (4229, 22)	1.0
  (4229, 24)	1.0
  (4229, 25)	1.0
  (4229, 185)	1.0
  (4229, 312)	44.0
  (4229, 313)	1136.0
  (4229, 314)	3.0
  (4229, 316)	345.0
  (4229, 317)	2.0
Fitting 2 folds for each of 4 candidates, totalling 8 fits
[CV 1/2] END .....................n_neighbors=1;, score=0.840 total time=   0.0s
[CV 2/2] END .....................n_neighbors=1;, score=0.829 total time=   0.0s
[CV 1/2] END .....................n_neighbors=5;, score=0.884 total time=   0.0s
[CV 2/2] END .....................n_neighbors=5;, score=0.878 total time=   0.0s
[CV 1/2] END ....................n_neighbors=10;, score=0.889 total time=   0.0s
[CV 2/2] END ....................n_neighbors=10;, score=0.887 total time=   0.0s
[CV 1/2] END ....................n_neighbors=15;, score=0.888 total time=   0.0s
[CV 2/2] END ....................n_neighbors=15;, score=0.888 total time=   0.0s
KNN -> The best parameter is 10.000 Accuracy: 0.869188

In [296]:
import numpy as np
A = np.array([1, 2, 3 ,4, 5, 6])

In [297]:
A.mean()

3.5

In [298]:
A.std()

1.707825127659933